//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionesServicioDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstacionesServicioBDEntities : DbContext
    {
        public EstacionesServicioBDEntities()
            : base("name=EstacionesServicioBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EstacionServicio> EstacionServicio { get; set; }
        public virtual DbSet<PuntoCarga> PuntoCarga { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
    }
}
